companieshouse/promise-to-file-web

routes.yaml

Routes have not yet been confirmed so this will serve as a placeholder until they are confirmed

placeholder routes.yaml

---

.gitignore

Added a scaled down git ignore based on extension web.

Added a git ignore file based on ext web but minimised for now

---

app.js
bin/www
package-lock.json
package.json
public/stylesheets/style.css
routes/index.js
routes/users.js
views/error.html
views/index.html
views/layout.html

This is just the basic project generated by express but modified to use the 'nunjucks' rather than the 'jade' templating engine. Still to do on this task (later PRs):
- Switch to using Typescript rather than just JS files
- Re-organise some files/folders (e.g. use 'dist' rather than 'bin')

LFA-1191 Basic skeleton Node JS express app using nunjucks

---

src/app.ts
src/model/page.urls.ts
src/model/template.paths.ts
src/routes/routes.ts
views/company-number.html
views/index.html

Adds prototype content for the welcome and company number screens as well as introducing some new TS artefacts to mimic the set-up in extensions.

LFA-1194 Add initial screens

---

package-lock.json
package.json
src/app.ts
src/bin/www.ts
src/logger.ts
tslint.json

Note, minor code changes required in order for source code to pass the lint quality checks.

Lfa 1186 integrate lint and logger

---

src/controllers/check.company.controller.ts
src/routes/routes.ts
views/check-company.html

Added nunjucks template 
To get it working added harcoded router values and a controller stub - these will be developed further on ticket lfa-1235

Added nunjucks template

---

package-lock.json
package.json
src/app.ts
src/controllers/company.number.controller.ts
src/model/error.messages.ts
src/model/govuk.error.data.ts
src/model/page.urls.ts
src/model/validation.error.ts
src/routes/routes.ts
test/controllers/company.number.controller.spec.unit.ts
views/company-number.html

This covers the basic validation for the company number screen including "no company number", "invalid company number" and "company number too long".

Company number screen validation

---

src/app.ts
src/http.logger.ts
src/logger.ts
src/properties.ts

LFA-1271 Correctly configure the Morgan HTTP logger

---

package-lock.json
views/company-number.html
views/layout.html

Also removed data event id on help with company number tag to potentially fix IE bug

Updated piwik on service

---

Makefile
package.json

Adding test and sonar targets for concourse task build-test-analyse to run

Adding new makefile targets for concourse sonar job

---

package-lock.json
src/bin/www.ts
src/client/apiclient.ts
src/session/store/redis.store.ts

Sonar highlighted some code smells so I've fixed them based on the recommended Sonar fixes.

Fixing code smells highlighted by Sonar

---

views/confirmation-still-required.html

Template work for LFA-1169 this complements LFA-1364

Renamed as this will be one of two confirmation screens

---

views/confirmation-not-required.html

The template for lfa-1364 counterpart can be found on PR: 
https://github.com/companieshouse/promise-to-file-web/pull/54

template for no longer required

---

src/app.ts
src/controllers/company.number.controller.ts
src/controllers/still.required.controller.ts
src/model/error.messages.ts
src/model/page.urls.ts
src/routes/routes.ts
test/controllers/still.required.controllers.spec.unit.ts
views/layout.html
views/still-required.html

Also updated survey link to match that shown here: https://companieshouse.atlassian.net/browse/LFA-1165

Added validation to still required page

---

package-lock.json
src/controllers/still.required.controller.ts
views/layout.html

Also fixed still-required page validation

Updated feedback link

---

test/routes/routes.spec.unit.ts

Unit test needed updating for the start screen text changes

Fixing unit test for start screen

---

src/controllers/confirmation.controller.ts

The call to the api was removed as the api was still work in progress. This has now been updated so enabling the api call again.

Re-enabling the call to the PTF api

---

src/client/apiclient.ts
src/properties.ts
test/global.setup.ts

API has moved to internal domain so updating location

Changed location of api to internalapi

---

package-lock.json
package.json
src/app.ts
src/controllers/confirmation.controller.ts
views/layout.html

Also did an npm audit fix which updated the nunjucks version

Added extra logging and added jquery back in for piwik

---

test/authentication/user/middleware/index.spec.unit.ts
views/confirmation-still-required.html

What happens next text amendment - updated
Text states new deadline – 28 days - already done
Late filing penalty  - already done
Fixed a lint error in a unit test -line too long.

Amend still required confirmation screen fixed lint error

---

views/not-eligible.html

Relates to https://companieshouse.atlassian.net/browse/LFA-1454

Updated not-eligible.html to be in line with latest requirements

---

views/warning.html

html file word change as specified on the ticket.

Warning screen text change

---

views/confirmation-still-required.html

Jira ticket at https://companieshouse.atlassian.net/browse/LFA-1536
This will open up a print window instead of a whole new page, with the required stylings.

Added print link to confirmation-still-required page

---

test/controllers/confirmation.controller.spec.unit.ts
views/not-eligible.html

Jira ticket at https://companieshouse.atlassian.net/browse/LFA-1642

Amended persistently late text and updated unit tests

---

test/feature.flag.spec.unit.ts

feature.flag.ts didn't have any unit tests, now it does

LFA-1668 Adding unit test for feature flags

---

src/app.ts
src/availability/middleware/service.availability.ts
src/model/template.paths.ts
test/availability/middleware/service.availability.spec.unit.ts
test/controllers/confirmation.controller.spec.unit.ts
test/global.setup.ts
views/service-unavailable.html

Adding a service unavailable screen that will show if the config SHOW_SERVICE_UNAVAILABLE_PAGE=on

LFA-1411 service unavailable screen

---

views/index.html

Jira ticket at https://companieshouse.atlassian.net/browse/LFA-1684

Add beta banner to index page

---

src/controllers/confirmation.controller.ts
src/model/eligibilityReasonCode.ts
test/controllers/confirmation.controller.spec.unit.ts
views/not-eligible.html

Jira ticket at https://companieshouse.atlassian.net/browse/LFA-1637

Add company already in prosecution option to not eligible page

---

views/confirmation-still-required.html

Changes will also address stories LFA-1766 and LFA-1767

LFA-1765 Text changes on the 'yes' journey confirmation screen

---

src/app.ts
views/layout.html

Replaced url so that favicon can be displayed for ptf.

OBJ-417 Favicon Required

---

README.md

OBJ-467 Readme for ptf web

---

package-lock.json
package.json

Resolves BI-7919: https://companieshouse.atlassian.net/browse/BI-7919

Updated redis to fix security dependency issue

---

src/authentication/company/middleware/index.ts
src/properties.ts
test/global.setup.ts

The `USE_FINE_GRAIN_SCOPES_MODEL` feature flag is no longer needed
FA-1072

Remove feature flag

---

src/authentication/user/middleware/index.ts
src/utils/request.utils.ts

Added a whitelist to ensure redirects are safe

wip - add whitelist to ensure redirects are safe

---

package-lock.json
package.json
src/client/axios.api.call.handler.ts

Updates to make vulnerabilities zero

---

README.md
package-lock.json
package.json
src/app.ts
src/csrf.middleware.ts
src/model/eligibilityReasonCode.ts
src/properties.ts
test/app.spec.unit.ts
test/authentication/company/middleware/index.spec.unit.ts
test/authentication/user/middleware/index.spec.unit.ts
test/availability/middleware/service.availability.spec.unit.ts
test/controllers/check.company.controller.spec.unit.ts
test/controllers/company.number.controller.spec.unit.ts
test/controllers/confirmation.controller.spec.unit.ts
test/controllers/healthcheck.controller.spec.unit.ts
test/controllers/still.required.controllers.spec.unit.ts
test/global.setup.ts
test/routes/routes.spec.unit.ts
test/session/session.spec.unit.ts
views/check-company.html
views/company-number.html
views/csrf-error.njk
views/csrf-token.njk
views/layout.html
views/still-required.html
views/warning.html

SEC-98 Implement CSRF tokens on web page journey for promise-to-file-web service

SEC-98 Implement CSRF tokens on web page journey for promise-to-file-web service
